### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by z-shug**

### CODE REVIEW

**Review by LazaroAlsina — CHANGES_REQUESTED** [review]
I am not sure what this is but please add more of line 43, like 5 x more.

**Comment by z-shug** [comment]
Oh ok perfect I can add those lines now. The original line was added to be a fun easter egg

**Review by LazaroAlsina — APPROVED** [review]
I love it, I approve this.

**Review by z-shug — COMMENTED** [review]
Help I can't approve my own request

**Pull request merged**
